name: GPex
version: ${project.version}
main: de.paulomart.gpex.GPex
Authors: [Paulomart]
softdepend: [NametagEdit, ServerCore]
commands:
   gpex:
      description: Does gpex stuff
permissions:
   gpex.help:
      description: /gpex help
      default: FALSE
   gpex.set:
      description: /gpex set
      default: FALSE
   gpex.reset:
      description: /gpex reset
      default: FALSE
   gpex.reload:
      description: /gpex reload
      default: FALSE
   