mysql:
  database: gpex
  host: localhost
  password: geheim123
  port: 3306
  user: user
  table: gpex3
useNameTagHooks: true
chatFormat: '%s: %s'
groupsConfig:
  webLoaded: false
  webURL: 'http://gpex.domain.de/gpex.yml'
  localPath: 'plugins/GPex/gpex.yml'