name: GPex
version: 3.0.2-Alpha
main: de.paulomart.gpex.GPex
Authors: [Paulomart]
softdepend: [NametagEdit, ServerCore]
commands:
   gpex:
      description: Does gpex stuff
permissions:
   gpex.help:
      description: /gpex help
      default: OP
   gpex.set:
      description: /gpex set
      default: OP
   gpex.reset:
      description: /gpex reset
      default: OP
   